# Generated by Django 4.0.4 on 2022-05-23 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='exp',
        ),
    ]
