# Generated by Django 4.0.4 on 2022-05-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.TextField()),
                ('type', models.TextField()),
            ],
            options={
                'db_table': 'groups',
            },
        ),
    ]
